package com.faction.clientportal.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

/**
 * Embedded comment on an Application — stored inside the Application row.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ApplicationComment {

    private String id;

    /** Username of the commenter (from JWT principal). */
    private String authorId;

    /** Snapshot of the commenter's display name at comment time. */
    private String authorName;

    /** Markdown content. */
    private String content;

    private LocalDateTime createdAt;

    private LocalDateTime updatedAt;

    /** If true, this comment was generated by the system and cannot be deleted. */
    @Builder.Default
    private boolean systemGenerated = false;
}
