package com.faction.clientportal.model;

import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDateTime;

/**
 * Maps an emailed @mention back to the thread a reply should be appended to.
 *
 * <p>The token travels in the outbound {@code Reply-To} address
 * ({@code faction+<token>@example.com}) and is the real access control on inbound mail:
 * it is unguessable and bound to a single recipient, so possession of it plus a matching
 * {@code From} address is what authorises appending a comment. A {@code From} header
 * alone is spoofable, which is why the token — not the sender — is the primary control.
 */
@Entity
@Table(name = "email_reply_token", indexes = {
        @Index(name = "idx_email_reply_token_message_id", columnList = "outboundMessageId"),
        @Index(name = "idx_email_reply_token_expires_at", columnList = "expiresAt")
})
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class EmailReplyToken {

    /** The token, generated by SecureRandom — never sequential, it is a bearer secret. */
    @Id
    @Column(length = 64)
    private String id;

    @Enumerated(EnumType.STRING)
    @Column(length = 32, nullable = false)
    private MentionTargetType targetType;

    /** Application id or vulnerability id, depending on {@link #targetType}. */
    @Column(nullable = false)
    private String targetId;

    /** Required for vulnerabilities, whose service API is always assessment-scoped. */
    private String assessmentId;

    /** Only this user may post through this token. */
    @Column(nullable = false)
    private String recipientUsername;

    /**
     * The {@code Message-ID} of the email this token was attached to, read back from
     * JavaMail after sending. Lets an inbound {@code In-Reply-To}/{@code References}
     * header resolve the thread when a provider strips sub-addressing from Reply-To.
     */
    @Column(length = 998)
    private String outboundMessageId;

    @Column(length = 1024)
    private String contextLink;

    private LocalDateTime createdAt;

    private LocalDateTime expiresAt;

    @Builder.Default
    @Column(nullable = false)
    private boolean revoked = false;

    public boolean isUsable(LocalDateTime now) {
        return !revoked && expiresAt != null && now.isBefore(expiresAt);
    }
}
