#!/usr/bin/env bash
#
# OWASP Faction 2 — first-run installer.
#
#   curl -fsSL https://raw.githubusercontent.com/factionsecurity/OWASP-Faction-2/main/install.sh | bash
#
# Pulls the images and writes a .env with freshly generated secrets. It does
# not start anything: read the .env it leaves you, then `docker compose up -d`.
#
# Environment:
#   FACTION_DIR       where to install         (default: ./owasp-faction-2)
#   FACTION_VERSION   version to pull          (default: latest)
#   HTTP_PORT         host port                (default: 8080)
#   PUBLIC_URL        URL people reach it at   (default: http://localhost:$HTTP_PORT)
#
# The whole body is a function called on the last line. Piping into a shell
# executes whatever has arrived so far, so a download cut off midway would
# otherwise run half an install — this way it runs none of it.

set -euo pipefail

RAW_BASE="https://raw.githubusercontent.com/factionsecurity/OWASP-Faction-2/main"

# No colour when the output is redirected or the terminal cannot show it.
if [ -t 1 ] && [ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]; then
  BOLD=$(tput bold); DIM=$(tput dim); RED=$(tput setaf 1)
  GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RESET=$(tput sgr0)
else
  BOLD=""; DIM=""; RED=""; GREEN=""; YELLOW=""; RESET=""
fi

say()  { printf '%s\n' "$*"; }
step() { printf '%s==>%s %s\n' "$BOLD" "$RESET" "$*"; }
warn() { printf '%s warning:%s %s\n' "$YELLOW" "$RESET" "$*" >&2; }
die()  { printf '%s error:%s %s\n' "$RED" "$RESET" "$*" >&2; exit 1; }

require_prerequisites() {
  step "Checking prerequisites"

  command -v docker >/dev/null 2>&1 \
    || die "docker is not installed. See https://docs.docker.com/get-docker/"

  # `docker compose`, the plugin — not the retired standalone docker-compose,
  # which cannot read this file.
  docker compose version >/dev/null 2>&1 \
    || die "the Docker Compose plugin is missing. Docker Desktop ships it; on Linux install docker-compose-plugin."

  # Catches the common case of Docker installed but Desktop not running, which
  # otherwise fails later with a less obvious error.
  docker info >/dev/null 2>&1 \
    || die "the Docker daemon is not responding. Start Docker Desktop (or dockerd) and run this again."

  command -v openssl >/dev/null 2>&1 \
    || die "openssl is not installed. It is what generates this install's secrets."

  command -v curl >/dev/null 2>&1 || die "curl is not installed."

  say "    docker $(docker version --format '{{.Server.Version}}' 2>/dev/null || echo '?'), compose plugin, openssl — all present"
}

# 48 random bytes, base64. The alphabet is A-Za-z0-9+/= — no '$', so nothing
# here can be re-interpreted when Compose interpolates the .env file.
generate_secret() {
  openssl rand -base64 48 | tr -d '\n'
}

fetch_compose_file() {
  step "Downloading docker-compose.yml"

  curl -fsSL "$RAW_BASE/docker-compose.yml" -o docker-compose.yml \
    || die "could not download docker-compose.yml from $RAW_BASE"

  # A captive portal or proxy error page returns 200 and would be written
  # straight over the file, so confirm this is actually the compose file.
  grep -q '^services:' docker-compose.yml \
    || die "the downloaded docker-compose.yml does not look like a compose file. Check your network."

  say "    $(wc -l < docker-compose.yml | tr -d ' ') lines"
}

# Read the image list out of the compose file rather than hardcoding it, so a
# new service or a bumped database version needs no change here.
pull_images() {
  local version="$1" image images

  images=$(sed -n 's/^[[:space:]]*image:[[:space:]]*\(.*\)$/\1/p' docker-compose.yml)
  [ -n "$images" ] || die "no images found in docker-compose.yml"

  step "Pulling images (version: $version)"
  say "${DIM}    The backend image is large — a first pull takes a few minutes.${RESET}"

  while IFS= read -r image; do
    [ -n "$image" ] || continue
    image="${image//\$\{FACTION_VERSION:-latest\}/$version}"
    say "    $image"
    docker pull --quiet "$image" >/dev/null \
      || die "could not pull $image. If this says 'no matching manifest', the version you asked for predates multi-architecture images — try FACTION_VERSION=latest."
  done <<< "$images"

  say "    done"
}

write_env_file() {
  local version="$1" port="$2" public_url="$3"

  step "Generating .env"

  local jwt_secret database_password storage_secret_key
  jwt_secret=$(generate_secret)
  database_password=$(generate_secret)
  storage_secret_key=$(generate_secret)

  # Written before it is filled in, so the secrets are never briefly readable
  # by everyone on a shared machine.
  install -m 600 /dev/null .env 2>/dev/null || { : > .env; chmod 600 .env; }

  cat >> .env <<ENV
# OWASP Faction 2 — generated by install.sh on $(date -u '+%Y-%m-%d %H:%M:%S UTC')
#
# The three secrets below were generated with: openssl rand -base64 48
# They are unique to this install. Back this file up; losing it does not lose
# your data, but changing these values has consequences noted on each.

# ─── Secrets ────────────────────────────────────────────────────────────────

# Signs every session token. Anyone holding it can mint a token for any user.
# Changing it signs everyone out; it invalidates nothing else.
JWT_SECRET=$jwt_secret

# Database password. Read by both the database and the backend.
# Change it after first start and the backend can no longer open the existing
# database — the password was baked into the volume when it was created.
DATABASE_PASSWORD=$database_password

# Object storage password (MinIO's root password). Also read by both.
STORAGE_SECRET_KEY=$storage_secret_key

# ─── Where this install lives ───────────────────────────────────────────────

# Port on the host. The application is served over plain HTTP; put it behind a
# reverse proxy that terminates TLS for anything beyond a private network.
HTTP_PORT=$port

# The URL people actually reach this install at. Emailed links — password
# resets, notifications, SLA digests — are built from it, so localhost works
# only while nobody else needs to open one.
PUBLIC_URL=$public_url

# ─── Version ────────────────────────────────────────────────────────────────

# latest tracks the newest full release, so \`docker compose pull && up -d\`
# upgrades. Pin a version (e.g. 2.0.1) to choose when that happens — tags are
# published without the \`v\` the release itself carries.
FACTION_VERSION=$version
ENV

  say "    .env written with mode 600 and three generated secrets"
}

main() {
  local dir="${FACTION_DIR:-./owasp-faction-2}"
  local version="${FACTION_VERSION:-latest}"
  local port="${HTTP_PORT:-8080}"
  local public_url="${PUBLIC_URL:-http://localhost:${HTTP_PORT:-8080}}"

  say ""
  say "${BOLD}OWASP Faction 2 — installer${RESET}"
  say ""

  require_prerequisites

  step "Preparing $dir"
  mkdir -p "$dir"
  cd "$dir"

  # Regenerating secrets over a working install is the one genuinely
  # destructive thing this script could do: a new DATABASE_PASSWORD cannot
  # open the volume the old one created, and the install stops starting.
  if [ -e .env ]; then
    warn "$dir/.env already exists — leaving it untouched."
    warn "Regenerating secrets would lock this install out of its own database."
    warn "To start over from nothing: docker compose down -v && rm .env"
    say ""
    say "Nothing to do. To upgrade an existing install instead:"
    say "    cd $dir && docker compose pull && docker compose up -d"
    exit 0
  fi

  fetch_compose_file
  pull_images "$version"
  write_env_file "$version" "$port" "$public_url"

  say ""
  say "${GREEN}${BOLD}Ready.${RESET} Start it with:"
  say ""
  say "    ${BOLD}cd $dir${RESET}"
  say "    ${BOLD}docker compose up -d${RESET}"
  say ""
  say "Then open ${BOLD}$public_url${RESET} and sign in as ${BOLD}admin / admin123${RESET}."
  say "${YELLOW}Change that password before anyone else can reach this install${RESET} — it is"
  say "seeded on first start and documented publicly."
  say ""
  say "${DIM}First start takes a few minutes: it runs every database migration and seeds"
  say "the default roles, users and vulnerability categories. Watch it with:"
  say "    docker compose ps"
  say "    docker compose logs -f backend${RESET}"
  say ""
  if [ "$public_url" = "http://localhost:$port" ]; then
    say "${DIM}Reaching this from another machine? Set PUBLIC_URL in .env to the URL people"
    say "will actually use, or emailed links will point them at their own localhost.${RESET}"
    say ""
  fi
}

main "$@"
