-- Phase 2 of the email integration.
--
-- 1. mention_queue only knew a contextLink (a URL string), which is enough to say
--    "you were mentioned" but not enough to put the comment in the email or to bind a
--    reply token to the thread it came from. Add the content snapshot and the target
--    identity.
-- 2. email_reply_token maps an emailed mention back to the thread a reply should join.
--
-- Both tables are Hibernate-owned, so the ALTER is guarded: Flyway runs before
-- Hibernate's schema bootstrap, and on a fresh database the table does not exist yet.
-- On fresh installs the entity definitions create these columns correctly anyway.

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'mention_queue') THEN
    ALTER TABLE mention_queue
        ADD COLUMN IF NOT EXISTS content_html TEXT,
        ADD COLUMN IF NOT EXISTS target_type VARCHAR(32),
        ADD COLUMN IF NOT EXISTS target_id VARCHAR(255),
        ADD COLUMN IF NOT EXISTS assessment_id VARCHAR(255);
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS email_reply_token (
    -- The token itself is the primary key: it travels in the Reply-To address, so it
    -- must be unguessable and is generated by SecureRandom rather than sequentially.
    id                  VARCHAR(64)  PRIMARY KEY,
    target_type         VARCHAR(32)  NOT NULL,
    target_id           VARCHAR(255) NOT NULL,
    assessment_id       VARCHAR(255),
    -- Only this user may post through this token. Usernames, not ids, to match the
    -- rest of the mention/notification system.
    recipient_username  VARCHAR(255) NOT NULL,
    -- Captured after send so an inbound In-Reply-To/References header can resolve the
    -- thread even when the provider strips sub-addressing from the Reply-To.
    outbound_message_id VARCHAR(998),
    context_link        VARCHAR(1024),
    created_at          TIMESTAMP    NOT NULL,
    expires_at          TIMESTAMP    NOT NULL,
    revoked             BOOLEAN      NOT NULL DEFAULT FALSE
);

-- Inbound matching looks a token up by id (the PK) or by outbound_message_id; the
-- expiry sweep scans expires_at.
CREATE INDEX IF NOT EXISTS idx_email_reply_token_message_id
    ON email_reply_token (outbound_message_id);
CREATE INDEX IF NOT EXISTS idx_email_reply_token_expires_at
    ON email_reply_token (expires_at);
